### ISSUE TITLE
Can't connect to Sony A6600

### ISSUE THREAD

**Issue by naixx** [dougforpres/NINASonyCameraPlugin#2]
I'm trying to connect the plugin, but it gives exception. Nina 3.1 HF2
Ascom is working fine

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at NINA.RetroKiwi.Plugin.SonyCamera.Drivers.CameraDriver.get_GainMin()
   at NINA.Equipment.Equipment.MyCamera.PersistSettingsCameraDecorator.get_GainMin() in C:\Projects\nina\NINA.Equipment\Equipment\MyCamera\PersistSettingsCameraDecorator.cs:line 242
   at NINA.WPF.Base.ViewModel.Equipment.Camera.CameraVM.ChooseCamera() in C:\Projects\nina\NINA.WPF.Base\ViewModel\Equipment\Camera\CameraVM.cs:line 370
```

**Comment by shurkanTwo** [comment]
@naixx This issue should be resolved in release version 1.0.0.4.
